### ISSUE TITLE
Reporte practica hilos

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/practica-de-hilos-DuilioAquino10#2]
[practica 2.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-DuilioAquino10/files/6498230/practica.2.pdf)

**Comment by Valentiin01** [comment]
calificación 18 hizo falta el objetivo, material y la descripción.

**Comment by josealfredo79** [comment]
Hay que agregar lo faltante para la proxima no se revisa practica sin el objetivo principal de la practica.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
